services:
  - type: web
    name: boxart
    env: node
    buildCommand: yarn install --frozen-lockfile && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_VERSION
        value: 18
